### PR TITLE
java 7 filewatcher tests

### PR DESCRIPTION
**Pull request by lxol**

### CODE REVIEW

**Comment by lxol** [comment]
it is Duration now ...

**Comment by fommil** [comment]
thanks a bunch for this!

I won't accept this just yet, as `ensime-server` has to build on java 7, but this can give me a good idea about what to expect from the new code.

BTW, you can use the notation `10 seconds` if you `import concurrent.duration._`.

**Comment by lxol** [comment]
I made an interesting observation that a new filewatcher  detects a change every 10 seconds. Almost exactly 10 secs. Regardless of whether I use `take` or `poll`. Looks like it is a limitation (feature?) of `inotify` that WatchService uses on linux. So statistically the detection will be ~ 5 secs.   

In your Spec all tests fails if Duration is 9sec and succeeds with 11 secs

**Comment by fommil** [comment]
interesting, I wonder if Windows has better performance and if there is a way to change the granularity of Linux.

**Comment by fommil** [comment]
hmm, we could set up appveyor for the java-7-filewatcher repo. If you create an `appveyor.yml` file like `ensime-server`, I'll add it as a service.

**Comment by lxol** [comment]
`appveyor.xml ` is in java7-filewatcher PR now. I copied it as it is from ensime-server.

**Pull request closed without merging**
